import 'package:sewa_barang_client/core/config/flavors.dart';

/// Resolve image URLs coming from the API.
///
/// Storage URLs generated by the backend may contain a `localhost` host
/// (from the server-side `APP_URL`), which is unreachable from a physical
/// device/emulator. In that case the host (and port) is rewritten to the
/// host (and port) of the configured API base URL, e.g.
/// `http://localhost:8000/storage/x.jpg` with base URL
/// `http://192.168.1.4:8000/api` becomes
/// `http://192.168.1.4:8000/storage/x.jpg`.
String? resolveApiImageUrl(String? url) {
  if (url == null || url.isEmpty) return url;
  final uri = Uri.tryParse(url);
  if (uri == null || !uri.hasScheme) return url;
  if (uri.host != 'localhost' && uri.host != '127.0.0.1') return url;

  final baseUri =
      Uri.tryParse(FlavorConfig.instance?.flavorValues.baseUrl ?? '');
  if (baseUri == null || baseUri.host.isEmpty) return url;

  return uri
      .replace(
        scheme: baseUri.scheme.isNotEmpty ? baseUri.scheme : uri.scheme,
        host: baseUri.host,
        port: baseUri.hasPort ? baseUri.port : uri.port,
      )
      .toString();
}
